name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: hp12c44
          MYSQL_DATABASE: farmaco_check
          MYSQL_USER: user
          MYSQL_PASSWORD: hp12c44
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3.14
        extensions: mysql, pdo_mysql, mbstring, openssl, xml, ctype, tokenizer, zip
        tools: composer, phpunit
        coverage: none

    - name: Install dependencies
      working-directory: ./farmaco-check-app
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Install Pest
      working-directory: ./farmaco-check-app
      run: composer require pestphp/pest --dev --no-progress --prefer-dist

    - name: Set up environment
      working-directory: ./farmaco-check-app
      run: cp .env.example .env

    - name: Clear Laravel cache
      working-directory: ./farmaco-check-app
      run: php artisan config:clear

    - name: Generate application key
      working-directory: ./farmaco-check-app
      run: php artisan key:generate

    - name: Run migrations
      working-directory: ./farmaco-check-app
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: farmaco_check
        DB_USERNAME: root
        DB_PASSWORD: hp12c44
      run: php artisan migrate --seed

    - name: Run tests
      working-directory: ./farmaco-check-app
      run: vendor/bin/pest
